//dam vinh hung
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Chỉ còn mình anh','Song/chi_con_minh_anh.mp3','Image/cs_damvinhhung')

insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Chờ đông','Song/cho_dong.mp3','Image/cs_damvinhhung')
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Cho vừa lòng em','Song/cho_vua_long_em.mp3','Image/cs_damvinhhung')
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Đà Lạt hoàng hôn','Song/da_lat_hoang_hon.mp3','Image/cs_damvinhhung')
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Đánh mất','Song/danh_mat.mp3','Image/cs_damvinhhung')
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Đành thôi người ơi','Song/danh_thoi_nguoi_oi.mp3','Image/cs_damvinhhung')
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Đêm thấy ta là thác đỗ','Song/dem_thay_ta_la_thac_do.mp3','Image/cs_damvinhhung')
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Đèn khuya','Song/den_khuya.mp3','Image/cs_damvinhhung')
insert into song(id_singer,name_song,path_song,picture_song)
values(1,N'Đợi em trong mơ','Song/doi_em_trong_mo.mp3','Image/cs_damvinhhung')

// cs thu minh
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Đời tư','Song/doi_tu.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Đường cong','Song/duong_cong.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Taxi','Song/taxi.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Xinh','Song/xinh.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Đừng yêu','Song/dung_yeu.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Vắng một ngày','Song/vang_mot_ngay.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Đừng tìm em nữa','Song/dung_tim_em_nua.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Mong gặp lại','Song/mong_gap_lai.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Ước gì','Song/uoc_gi.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Nhớ anh','Song/nho_anh.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Phút yêu đầu','Song/phut_yeu_dau.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Trách người đi','Song/trach_nguoi_di.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Thơ ngây','Song/tho_ngay.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Phố quên','Song/pho_quen.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Cô đơn','Song/co_don.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Ước mơ','Song/uoc_mo.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Thuyền và biển','Song/thuyen_va_bien.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Ngọc ngà Việt Nam','Song/ngoc_nga_viet_nam.mp3','Image/cs_thuminh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(8,N'Yêu mình anh','Song/yeu_minh_anh.mp3','Image/cs_thuminh.jpg')

// ha anh tuan
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'An','Song/an.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Cô gái và cây dương cầm','Song/co_gai_va_cay_duong_cam.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Lạc lối','Song/lac_loi.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Người','Song/nguoi.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Người con gái ta thương','Song/nguoi_con_gai_ta_thuong.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Radio','Song/radio.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Tái bút anh yêu em','Song/tai_but_anh_yeu_em.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Tháng tư là lời nói dối của em','Song/thang_tu_la_loi_noi_doi_cua_em.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Thương em','Song/thuong_em.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Xuân thì','Song/xuan_thi.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Giấc mơ chỉ là giấc mơ','Song/giac_mo_chi_la_giac_mo.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Cứ thế','Song/cu_the.mp3','Image/cs_haanhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(21,N'Hoàng hôn tháng tám','Song/hoang_hon_thang_tam.mp3','Image/cs_haanhtuan.jpg')

// lam truong
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Bổng dưng muốn khóc','Song/bong_dung_muon_khoc.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Cảm ơn người tình','Song/cam_on_nguoi_tinh.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Chợt nghe bước em về','Song/cho_nghe_buoc_em_ve.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Con đường tình yêu','Song/con_duong_tinh_yeu.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Đợi vài giây','Song/doi_vai_giay.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Em có biết chăng','Song/em_co_biet_chang.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Em quên mùa đông','Song/em_quen_mua_dong.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Giây phút này','Song/giay_phut_nay.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Lãng quên chiều thu','Song/lang_quen_chieu_thu.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Những lời dối gian','Song/nhung_loi_do_gian.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Nơi bình yên','Song/noi_binh_yen.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Thôi anh hãy về','Song/thoi_anh_hay_ve.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Tiển bạn lên đường','Song/tien_ban_len_duong.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Tình đơn phương','Song/tinh_don_phuong.mp3','Image/cs_lamtruong.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(32,N'Tình thôi xót xa','Song/tinh_thoi_xot_xa.mp3','Image/cs_lamtruong.jpg')

//mtp
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Âm thầm bên em','Song/am_tham_ben_em.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Anh sai rồi','Song/anh_sai_roi.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Buông đôi tay nhau ra','Song/buong_doi_tay_nhau_ra.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Chắc ai đó sẽ về','Song/chac_sai_do_se_ve.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Chạy ngay đi','Song/chay_ngay_di.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Chúng ta không thuộc về nhau','Song/chung_ta_khong_thuoc_ve_nhau.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Cơn mưa ngang qua','Song/con_mua_ngang_qua.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Em của ngày hôm qua','Song/em_cua_ngay_hom_qua.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Không phải dạng vừa đâu','Song/khong_phai_dang_vua_dau.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Nắng ấm xa dần','Song/nang_am_xa_dan.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Nơi này có anh','Song/noi_nay_co_anh.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'Remember me','Song/remember_me.mp3','Image/cs_mtp.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(2,N'You of yesterday','Song/you_of_yesterday.mp3','Image/cs_mtp.jpg')

// bui anh tuan
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Bí mật không tên','Song/bi_mat_khong_ten.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Buông','Song/buong.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Chia tay','Song/chia_tay.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Hẹn một mai','Song/hen_mot_mai.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Hoang mang','Song/hoang_mang.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Im losing you','Song/im_losing_you.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Lặng yên','Song/lang_yen.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Mãi mãi là của nhau','Song/mai_mai_la_cua_nhau.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Mơ hồ','Song/mo_ho.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Nỗi nhớ vô hình','Song/noi_nho_vo_hinh.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Nơi tình yêu kết thúc','Song/noi_tinh_yeu_ket_thuc.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Nói với em rằng','Song/noi_voi_em_rang.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Thuận theo ý trời','Song/thuan_theo_y_troi.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Trò đùa của tạo hóa','Song/tro_dua_cua_tao_hoa.mp3','Image/cs_buianhtuan.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(4,N'Xin em','Song/xin_em.mp3','Image/cs_buianhtuan.jpg')

//phan manh quynh
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Có chàng trai viết lên cây','Song/co_chang_trai_viet_len_cay.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Hà Lan','Song/ha_lan.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Hãy ra khỏi người đó đi','Song/hay_ra_khoi_nguoi_do_di.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Khi phải quên đi','Song/khi_phai_quen_di.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Nghĩ lại','Song/nghi_lai.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Người khác','Song/nguoi_khac.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Nước ngoài','Song/nuoc_ngoai.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Tôi chỉ muốn nói','Song/toi_chi_muon_noi.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Tôi muốn quên em','Song/toi_muon_quen_em.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Tri kỷ','Song/tri_ky.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Từ đó','Song/tu_do.mp3','Image/cs_phanmanhquynh.jpg')
insert into song(id_singer,name_song,path_song,picture_song)
values(5,N'Khi người mình yêu khóc','Song/khi_nguoi_minh-yeu_khoc.mp3','Image/cs_phanmanhquynh.jpg')