//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rs_content.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYLIST
    {
        public int ID_PLAYLIST { get; set; }
        public string NAME_PLAYLIST { get; set; }
        public Nullable<int> ID_USER { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
