//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rs_content.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONGPLAYLIST
    {
        public int ID_PLAYLIST { get; set; }
        public int ID_SONG { get; set; }
    }
}
