//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_music_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.PLAYLISTs = new HashSet<PLAYLIST>();
        }
    
        public int ID_USER { get; set; }
        public string NAME_USER { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string AVARTAR { get; set; }
        public Nullable<int> decentralization { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAYLIST> PLAYLISTs { get; set; }
    }
}
